// let nums=[1,2,3,4,5];
// const square=nums.map((nums)=>nums*nums);
// console.log(square);
// let sum=square.reduce((acc,curr)=>acc+curr,0);
// console.log(sum);
// let avg=sum/nums.length;
// console.log(`The average of the squares is: ${avg}`);
let para1=document.createElement("p");
para1.innerText="Hey, I'm red";
document.querySelector( "body" ).append(para1);
para1.classList.add("red");
let h3=document.createElement("h3");
h3.innerText="Hey,  I'm blue";
document.querySelector("body").append(h3);
h3.classList.add("blue");
let div=document.createElement("div");
let h1=document.createElement("h1");
let para2=document.createElement("para2");
h1.innerText="I'm in a div";
para2.innerText="Me too";
div.append(h1);
div.append(para2);
div.classList.add("box");
document.querySelector("body").append(div);